In [1]:
from tensorflow.keras.preprocessing.text import one_hot
import tensorflow as tf

In [2]:
### sentences
sent=['the glass of milk',
     'the glass of juice',
     'the cup of tea',
     'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [3]:
## Define the vocabulary size
voc_size = 20

In [4]:
### One Hot Representation
one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[9, 10, 17, 14],
 [9, 10, 17, 18],
 [9, 16, 17, 6],
 [11, 19, 18, 13, 15],
 [11, 19, 18, 13, 8],
 [15, 9, 9, 17, 4],
 [1, 1, 15, 13]]

These are the index numbers where the value is one rest is zero remeber vocabluray

In [5]:
## word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [6]:
import numpy as np

In [7]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[ 0  0  0  0  9 10 17 14]
 [ 0  0  0  0  9 10 17 18]
 [ 0  0  0  0  9 16 17  6]
 [ 0  0  0 11 19 18 13 15]
 [ 0  0  0 11 19 18 13  8]
 [ 0  0  0 15  9  9 17  4]
 [ 0  0  0  0  1  1 15 13]]


In [8]:
## feature representation
dim = 10

internally it is using Word2Vec 

In [9]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam','mse')

c:\Users\shrey\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [16]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (7, 8, 10)             │           200 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 200 (800.00 B)

 Trainable params: 200 (800.00 B)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 176ms/step


array([[[-0.00427974,  0.03287673, -0.0436632 ,  0.0301415 ,
         -0.01030298,  0.04720904, -0.03460795, -0.00801393,
          0.02098826, -0.04413331],
        [-0.00427974,  0.03287673, -0.0436632 ,  0.0301415 ,
         -0.01030298,  0.04720904, -0.03460795, -0.00801393,
          0.02098826, -0.04413331],
        [-0.00427974,  0.03287673, -0.0436632 ,  0.0301415 ,
         -0.01030298,  0.04720904, -0.03460795, -0.00801393,
          0.02098826, -0.04413331],
        [-0.00427974,  0.03287673, -0.0436632 ,  0.0301415 ,
         -0.01030298,  0.04720904, -0.03460795, -0.00801393,
          0.02098826, -0.04413331],
        [-0.03041179, -0.0411101 , -0.04354725,  0.03092651,
         -0.03649757, -0.00564735,  0.02771444, -0.00647031,
          0.01037618,  0.00741066],
        [ 0.01346021,  0.00918895,  0.00467954,  0.0026355 ,
         -0.01816039, -0.00922077, -0.02823778,  0.04653994,
          0.01705578,  0.00628842],
        [-0.0074389 ,  0.00468097, -0.03547866, -0.0

In [21]:
embedded_docs

array([[ 0,  0,  0,  0,  9, 10, 17, 14],
       [ 0,  0,  0,  0,  9, 10, 17, 18],
       [ 0,  0,  0,  0,  9, 16, 17,  6],
       [ 0,  0,  0, 11, 19, 18, 13, 15],
       [ 0,  0,  0, 11, 19, 18, 13,  8],
       [ 0,  0,  0, 15,  9,  9, 17,  4],
       [ 0,  0,  0,  0,  1,  1, 15, 13]])

In [22]:
embedded_docs[0]

array([ 0,  0,  0,  0,  9, 10, 17, 14])

In [13]:
print(embedded_docs[0].shape)

(8,)


In [14]:
embedded_docs[0] = tf.reshape(embedded_docs[0], (1, -1))  # For single sequence


In [17]:
np.expand_dims(embedded_docs[0], axis=0)

array([[ 0,  0,  0,  0,  9, 10, 17, 14]])

In [25]:
import numpy as np
ans = model.predict(np.expand_dims(embedded_docs[0], axis=0))
ans, ans.shape

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step


(array([[[-0.00427974,  0.03287673, -0.0436632 ,  0.0301415 ,
          -0.01030298,  0.04720904, -0.03460795, -0.00801393,
           0.02098826, -0.04413331],
         [-0.00427974,  0.03287673, -0.0436632 ,  0.0301415 ,
          -0.01030298,  0.04720904, -0.03460795, -0.00801393,
           0.02098826, -0.04413331],
         [-0.00427974,  0.03287673, -0.0436632 ,  0.0301415 ,
          -0.01030298,  0.04720904, -0.03460795, -0.00801393,
           0.02098826, -0.04413331],
         [-0.00427974,  0.03287673, -0.0436632 ,  0.0301415 ,
          -0.01030298,  0.04720904, -0.03460795, -0.00801393,
           0.02098826, -0.04413331],
         [-0.03041179, -0.0411101 , -0.04354725,  0.03092651,
          -0.03649757, -0.00564735,  0.02771444, -0.00647031,
           0.01037618,  0.00741066],
         [ 0.01346021,  0.00918895,  0.00467954,  0.0026355 ,
          -0.01816039, -0.00922077, -0.02823778,  0.04653994,
           0.01705578,  0.00628842],
         [-0.0074389 ,  0.00468097